---
title: SMT Solving
---

# Introduction

SMT: Sat-Modulo Theory

-> n > 0 => n - 1 <= n
-> $\neg(aux > 0) $ /\ $(res + aux = a + b)$ /\ $aux \geq 0$

why3 -> WP precond => WP(..., postcond)
obtains conditions like these and delegates the satisfaction of such a formula to a SMT solver

$\underbrace{b \geq 0 \Longrightarrow a + b = a + b /\ b \geq 0}_{P(a, b)}$

$\forall a, b$, $P(a, b)$

- basic mechanisms of SMT-Solving
- How it connect to tools such as why3


# SAT-Solving

SAT-Problem

Propositional Logic: variables -> propositional $Var = {p, q, ...}$ $p, q$ can be $true / false$

$+$ Logic connectors, $\land, \lor, \implies, \neg, \cdots$

Grammar generate a PL formula.

$F \longmapsto P$
$\longmapsto \neg F$
$\longmapsto F \land F | F \lor F | F \Longrightarrow F$

why3 begin to compute $\land$ and then $\lor$ !

::: {.notes}
$p \Longrightarrow q \Longrightarrow t \Longleftrightarrow p \Longrightarrow (q \Longrightarrow t)$
:::

### Satisfaction of a PL formula ?
 (Complete this part, please !!!)

 - f: PL blabla -> true -> false
- an interpretation: I is Var -> {true, false}
- I is extended to any PL formula
  - if $f = p \in Var$  $I(f) = I(p)$
  - if $f = \neg f'$  $I(f) = \text{true iff} I(f') = false$
  - if $f = f_1 \lor (\land) f_2$ $I(f) = \text{true iff} I(f_1) = true \text{or / and} I(f_2) = true$
  - if $f = f_1 \Longrightarrow f_2$  $I(f) = \text{true iff is} I(f_1) \text{is true then} I(f_2) \text{is true (otherwise false)}$

- $f$ is satisfied by $I$ ($I \models f$) iff $I(f)$ is true
- $f$ is satisfiable iff $\exists I, I \models f$
- $f$ is valid iff $\forall I, I \models f$ (a tanto logy ???)

ex:

$\forall a, \forall b, P(a, b)$
- why3: $f$ valid
- SAT: satisfiability of a formula
  $\Longrightarrow f$ is unsatisfiable: $\forall I, I(f) = false \Longleftrightarrow \forall I, I(\neg f) = true \Longleftrightarrow I(\neg f) is valid$

$\Longrightarrow g \text{valid} \Longleftrightarrow \neg g \text{is unsatisfiable}$

This is called *Proof by refutation*

Usually, $g$ wil be writtent as some hypothesis implies some conclusion, so $\neg g = hypothesis \land \neg concl$ 

### SAT-problem

$f$: PL formula -> answers: is the formula satisfiable ??? 

graph: f --> SAT, SAT --> yes, SAT --> no (please create simple tikz graph here according to relations given !!!)

$#$ if interpretations: $2^n$
Decidable: $\exists$ algorithm to solve it 
NP-Complete: $\Longrightarrow$ no efficient algorithm !!!

May fail due to lack of ressources Mem | time

#### An (old) method ot solve the problem

(Make good definition of CNF equivalent formula here !!!)

$f$: PL formula
$\Longrightarrow$ transform it in a conjunctive normal formula (CNF) equivalent formula 

CNF: $C_1 \land C_2 \land \cdots \land C_n$ $C_i$: clause subformula... $C_i = f^i_1 \lor f^i_2 \lor \cdots \lor f^i_n$ with $f^i_j$ a litterals $\in Var \lor {\neg p, p\in Var}$

EX: (generate example here !)

(Admitted) For every $f$ (PL formula), $\exists$ a PL formula in CNF which is equivalent to $f$.


So we restrict the SAT problem to CNF satisfiability.

graph: f --> CNF, CNF -equiv f-> SAT, SAT --> yes, SAT --> no (make tikz graph here !!!)

Remark:

- $P \land (a \lor \neg a \lor \cdots \lor \cdots) \land Q \underbrace{\longrightarrow}_{\text{simplify} P \land Q$
- $P \land \underbrace{a}_{\text{unit clause (contains only 1 litteral)}} \land Q$
  if $(P \land a \land Q = true$) then ($a = true$, $P \land Q$ = true) enforces the value of a. => solve the problem $P \land Q$

#### DPLL (Davis-Putman-Logeman-Lovelang 1962)

(make good and structured definition here !!)

$P$ = PL CNF formula
For $x \in Var \lor {\neg p, p \in Var}$ a litteral, $P[x]$ is the formula obtained enforcing the waluve of $x$ to true, the result is satisfied.

- if $x$ is in a clause of $P$, $P = A \land (\cdots \lor x \lor \cdots) B$ => $P[x]  = A \land B$
- if $x$ contains only one clause, $P = (\cdots \lor x \lor \cdots)$ => $P[x] = true$
- if $\neg x$ appears in $P$, then $P = A \land (\cdots \lor \neg x \lor \cdots) \land B$ => $P[x] = A \land (\cdots \lor \cdots) \land B$
- if $\neg x$ appears in a unit clause, $P = A \land \neg x \land B$ => $P[x] = false$

DPLL(P) = returns true iff $P$ is satisfialbe

- if $P = true$ then return true
- if $P = false$ then return false
- if $P$ contains a unit clause $x$, then return DPLL($P[x]$) 

Pick a variable $x$ in $P$ and then we try: return DPLL($P[x]$) or (it's a lazy operator !) DPLL($P[\neg x$])

- algo terminates !!!

  Hoare Logic

  the variant is the number of variables in $P$ (it decreases by 1 at each call)

- algo return true iff $P$ is satisfiable

Example: 
$P = (p \lor q \lor r) \land (\neg q \lor r) \land \neg r \land (\neg p \lor q \lor r)$
DPLL($P$) = 

- $P[\neg r] = (p \lor q) \land \neg q \land (\neg p \lor q)$
- $P[\neg r, \neg q] = p \land \neg p$
- $P[\neg r, \neg q, p] = False$

=> $P$ is unsatisfiable

if DPLL(Q) = $Q[p, \neg r, \cdots] = True$, we know how to set variables to have true => $Q$ is satisfiable !!!

### Course 2

enhancement to DPLL: CDCL Conflict Driven Clause Learning (1996-99)
  
  - More than 100000 variables
  - Millions of clauses
  => very efficient !!

Based on decision trees (Can you make here a decision tree ??? With each node a variable, left branch is true and right branch is false)
We want to see if set a variable will go to deadlocks (leaf False) or not...

Back to our problem...
Remember: we use why3 to have some formula and then we ask us if it's valid

$a \geq 0 \land b \geq 0 \Longrightarrow a + b \geq b + c$

- variables: $a, b, c \in \mathbb{Z}$ (Domain of the variables)
- functions: $+: \mathbb{Z}^2 \longrightarrow \mathbb{Z}$ (computes new values in the domain)
- predicates: $\geq: \mathbb{Z}^2 \longrightarrow \{True, False\}$

=> First order logic formula !!!

### First order logic formula

It's how we describe a formula.
It contains quantifiers ! ($\exists$, $\forall$)

$Var = {a, b, c, \cdots}$ variables
$D$: domain of value for $Var$ in $Var$
$\mathbf{F} = {f: D^R \longrightarrow D, R \in \mathbb{N}}$ funcitons (including functions with no parameters which are just CONSTANTS !!!)
$\mathbf{P} = {P: D^P \longrightarrow {True, Valse, k \n \mathbb{N}}}$ predicates

Now it's possible to build a term

#### Building a term

(Value in $D$ !)

- $a \in Var$, $a$ is a term
- if $t_1, \cdots, t_k$ are terms $f(t_1, \cdots, t_k)$ is term for $f \in \mathbf{F}$

#### Building an axiom

- True, False are axioms.
- if $t_1, \cdots, t_k$ are terms, $p(t_1, \cdots, t_k)$ is a term for $p \in \mathbf{P}$

#### Building a formula

- if $f$ is axiom then $f$ is a formula.
- if $f_1, f_2$ are formulas then $f_1 \land f_2, f_1 \lor f_2, f_1 \Longrightarrow f_2, \neg f_1$ are formulas.

We don't use it $\Downarrow$ in this lecture !!!

- if $f$ is a formula, then $\exists x f$ is a formula
- if $x \in Var$ is a formula, then $\forall x f$ is a formula

Go back to this: 
$a \geq 0 \land b \geq 0 \Longrightarrow a + b \geq b + c$
We need:

- Logic: $\land, \lor, \cdots$
- integer numbers, $+, \geq, leq, \cdots$ (it's a theory !! (Can you short define it ???))

Theory is a set of formulas that describe some particular things and gives the rules about a domain, some functions and predicates on it.

(For integers, it could be arithmetic on integers)

$\Longrightarrow$ a formula is valid in some theory $\mathbf{T} \longrightarrow (\mathbf{T}-valid)$ iff the formula is a consequence of $\mathbf{T}$.
I want that $\forall I$, $I$ is an interpretation, $I \models \mathbf{T} \Longrightarrow I \models f$

We just assume that a sef of elements works, and then we can deduce something from our formula !

### Examples

#### Theory about integer numbers

- $+, \leq, \cdots$
- $*$

#### Theory of arrays

$\underbrace{a[i]}_{\text{select}}$
$\underbrace{a[i]:=x}_{\text{store}}$

Our domain include arrays
$D \include arrays$
$\mathbf{F} \include {store (store(a, i, x)), select (select(a, i))}$
axioms $\forall a, x, z, y, \ select(store(x, z, y), z, y) = y$

#### Equality with uninterpreted functions (EUF)

$D, \mathbf{F}, \mathbf{P} \include {\underbrace{\approx}_{\text{equality on}\ D}}$

Axioms:

$\approx$ is an equivalence:

- R: $\forall x, x \approx x$
- S: $\forall x, y, x \approx y \Longrightarrow y \approx y$
- T: $forall x, y, z, x \approx y \Longrightarrow y \approx z \Longrightarrow x \approx z$

Each function (in $\mathbf{F}$) and predicate (int $\mathbf{P}-{\approx}$) is congruent.
  
  - $\forall x, y, x \approx y \Longrightarrow f(x) \approx f(y)$ (for $f \in \mathbf{F}$ with one parameter... Same for 2 parameters etc... Make here a small proof !!!)
- $\forall x_1, x_2, y_1, y_2, x_1 \approx y_1 \Longrightarrow x_2 \approx y_2 \Longrightarrow f(x_1, x_2) \approx f(y_1, y_2)$ (for 2 parameters)
  - $\forall x, y, x \approx y \Longrightarrow (p(x) \Longleftrightarrow p(y))$ (1 param $p \in \mathbf{P}$)


### SMT Solving

- Logic => solving a propositional logic (using SAT Solver) is very efficient
- theories => solving problems with ad hoc theories (but no logic inside) can also be very efficient

However, trying to use both is difficult !!

(make a graph here !!! Here is the decription of the graph :)
Algorithm DPLL(T) with T a theory

We take $f$ a formula: FOL, uses T, quantifier-free
We translate it to a propositional formula (it's a kind of abstraction !)

$A(f)=$ propositional logic formula which is able to use a SAT solver.

The SAT solver can answer yes or no.

If it's no, it means that $A(f)$ is unsatisfiable => $f$ is unsatisfiable too !!

If it's yes, we obtain a model/interpretation $M$  of $A(f)$ such as $M \models A(f)$
=> concretize $M_T = A^{-1}(M)$ and this will be pushed in an ad hoc solver of the Theory T which responds to the question 'is M_T satisfiable ?'
If it answer yes, $M_T \models f$, $f$ is satisfiable
If it aswer no, we redefine the problem using $\neg M$.
Sometimes it fail (decidability, lack of ressources, ...)

(End of description of the graph !)

- $A(f)$: replace each axiom in $f by a propositional variable.
  Example:
  $f = (a + b \leq c \land a > 0 \Longrightarrow b + c < a) \lor a \leq 0$

  - $p \longrightarrow a + b \leq c$
  - $q \longrightarrow a > 0$
  - $r \longrightarrow b + c < a$

  $A(f) = (p \land q \Longrightarrow r ) \lor \neg q$

- $A^{-1}(M)$ replaces each propositional variable by it initial definition.
  Example:
  Suppose $M = q \land \neg r \models A(f)$
  $A^{-1}(M) = a > 0 \land \neg(b + c < a)$

#### Example EUF

$P = g(a) = c \land (f(g(a)) \neq f(c) \lor g(a) = d) \land c \neq d$

- $Var = {a, c, d}$
- $D$ is arbitrary
- $\mathbf{F} = {f, g}$
- $\mathbf{P} = {=}$

$A(P) = p_1 \land (\neg p_2 \lor p_3) \land \neg p_4$

- $p_1 \longrightarrow g(a) = c$
- $p_2 \longrightarrow f(g(a)) = f(c)$
- $p_3 \longrightarrow g(a) = d$
- $p_4 \longrightarrow c = d$

... SAT solving $\longrightarrow M = p_1 \land \neg p_2 \land \neg p_4$
$\Longrightarrow M_T = A^{-1}(M) = g(a) = c \land f(g(a)) \neg f(c) \land c \neg d$
is $M_T$ EUF satisfiable ??? $g(a) = c \Longrightarrow f(g(a)) = f(c)$ so $M_T$ is not T-satisfiable !!!

Add the clause $\neg M$ to $P$. Now we redo same computation of $A(P) \land \neg M \Longrightarrow p_1 \land(\neg p_2 \lor p_3) \land \neg p_4 \land(\neg p_1 \lor p_2 \lor p_4)$
and we redo the computation.
(continues the example here !!!)

At some point, we reach that $P$ is unsatisfiable.

How work the refine ??

$A(f) \Longrightarrow M \lor f \Longrightarrow M_T$ if $M_T$ is false, adding $\neg M_T$ to $f$ will not change $f$.


Next course 
Pickt slides from Matteo's exercices
1. SAT solving -> SAT problems
2. Theories -> FOL formulas with ro quantifies
3. +quantifiers


### FOL formula -> SAT ???

#### Definition

- Universal formula: $\forall x_1, x_2, \cdots, x_k \phi$ where $\phi$ is quantifier free.
- a closed formula is FOL formula where every variable has been introduced beforeland by a quantifier (a free variable: a variable which has no been introduced by a quantifier)
  Ex:
  - $\forall a, b, c, \ \ a + b < c \lor b > 0$ closed, universal
  - $\forall a \ \ a + b < c \lor \exists c \ c < b$ not closed, universal
  - $\forall a, b \ a + b < 0 \ \exists 0 \ c < b$ closed, not universal

- Closed instance: def $\phi$ FOL formula quantifier-free
  A closed instance of $\phi$ is a formula $\theta(\phi)$ 
    - $\theta(\phi)$ is closed
    - $\theta$ is a substitution: it associates an expression to each of variable of this formula
      $\theta(\phi)$ is the formula $\phi$ where every variable $x \in \phi$ has been replace by $\theta(x)$
      Ex: $\forall x,y,z \ \phi \ \phi \equiv x = y \Longrightarrow f(z) = f^2(y)$
          $\theta: {x \leftarrow f^2(a), y \leftarrow b, z \leftarrow f(b)}$ where $a, b$ are constants.
          $\theta(\phi) = f^2(a) = b \Longrightarrow f^2(b) = f^2(b)$ -> hole formula is closed...

::: {.notes}
Universal formula are easy to satisfy ???
:::

#### Theorem of Herbrand (1930) (Admitted)

A set of quantifier-free FOL formula is unsatisfiable iff there exist a finite set of unsatisfiable closed instances 

Ex: $\neg (\forall a, b, c \ a + b \geq 0 \Longrightarrow c \geq b) \Longleftrightarrow \exists a, b, c \ a + b \geq 0 \land c < b$

So we will have $\exists x_1, x_k$ such that $\neg \phi$...

TestSat(\phi (quantifier \ free)):
  F:= \phi
  while F is satisfiable:
    let \theta be a substitution such that \theta(\phi) is a closed instance
    F:= F \lor {\theta(\phi)}
  // F is unsatisfiable
  // F contains a finite number of closed instances.
  return False // \phi is unsat (thm of Herbrand)

::: {.notes}
If satisfiable, then infinite loop $\Longleftrightarrow$ semi-algorithm !!!
:::

::: {.notes}
Still on going research !!! trigger, unification, e-matching, ...
:::

Ex1: $\phi \ {\forall z\ z = f(z) \land \forall x, y \ g(x, y) \neq f^2(y) \land g(a, a) = a}$
ENF: arbitrary domain of values, ${a, b}$ are 2 constants

1. $\theta_1: x \leftarrow a,\ y \leftarrow b$
  $a = f(a) \land g(a, b) \neq f^2(b) \land g(a, a) = a$
  $F = {\theta_a(\phi)}$

2. $\theta_2: x \leftarrow f(a), g \leftarrow f(b), z \leftarrow f(a)$
  $f(a) = f^2(a) \land g(f(a), f(b)) \neq f^3(b) \land g(a, a) = a$
  $F = {\theta_1(\phi), \theta_2(\phi)}$

3. $\theta_3: x \leftarrow a, g \leftarrow a, z \leftarrow a$
  $a = f(a) \land g(a, a) \neq f^2(a) \land g(a, a) = a$
  $F = {\theta_1, \theta_2, \theta_3}$

  Return false

Ex:
all humans are mortel
all greeks are human
then all greeks are mortel

Model:$(\forall x, \ H(x) \Longrightarrow M(x)\land G(x) \Longrightarrow H(x))\Longrightarrow G(x) \Longrightarrow M(x)$
Is this formula valid ???

Compute result using refutation... unsatisfibility of $\neg \phi$

Model:$(\forall x, \ H(x) \Longrightarrow M(x)\land G(x) \Longrightarrow H(x))\land (\exists x, \ G(x) \land \neg M(x)$
It's not a universal formula !!!!!

$\neg \phi = \forall x, y, \ \left[(\neg H(x) \lor M(x)) \land (\neg G(y) \lor H(y)) \land G(s) \land \neg M(s)\right]$ if $s$ is a constant, it is closed.
So this formula is universal and close !

$\theta: x \leftarrow b; y \leftarrow b$ (the only possible closed instance !)
$\theta(\neg \phi) = (\neg H(s) \lor M(b)) \land (\neg G(s) \lor H(s)) \land G(s) \land \neg M(s)$
$F= {\theta(\neg \phi)}$ is F satisfiable ? No $\Longrightarrow$ not satisfiable !!!

$\neg \phi$ is unsatisfiable so the conclusion is valid !!!

How to transform a formula to universal formula ???

FOL formula |                                 | FOL formula
(arbitrary) |-> preserves unsatisfiability -> | Universal 
closed      |                                 | closed

#### Transformation

1. Remove $\Longrightarrow, \Longleftrightarrow$, put the $\neg$ such that they only apply on variables/predicates.

2. Each quantifier introduces a fresh variable.
  $(\forall x, \cdots) \land (\forall x, \cdots) \land (\exists x, \cdots) \Longrightarrow (\forall x, \cdots) \land (\forall y, \cdots) \land(\exists z, \cdots)$

3. Skolenization (Tharalf Albert Skolen, 1887-1963) which remove $\exits$ by introducing fresh functions
  Extract subformula $\exists y, \ \psi$. $\psi$ may depend on other variables $x_1, \cdots, x_k$.
  We pick fresh function $f$ with fresh name and we replace the subformula by $\psi[y \leftarrow f(x_1, \cdots, x_k)]$

  ::: {.notes}
  A constant is a function with no parameters !!!
  :::

  Ex: $\forall x, \exits y, \ P(x, y) \longrightarrow \forall x, \ P(x, f(x))$ with $f$ a fresh function.
  Ex: $\forall x, \exists y, \ Q(y) \longrightarrow \forall x, \ Q(s)$ with $s$ a fresh constant.
  Ex: $\forall x,y \exists z, \ R(x, y, z) \longrightarrow \forall x, y, \ R(x, y, g(x, y))$

4. Put every $\forall$ at the begining. It's awlays equivalent because we have fresh names of variables !

