project:
  type: website
  title: "Software Modeling and Verification"
  output-dir: ../_site

website:
  navbar:
    # background: primary
    search: true
    right:
      - text: Language
        icon: globe
        menu:
          - text: "English"
            href: index.html
          - text: "French"
            href: fr/index.html
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course"
        contents: "ch*.qmd"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
  pdf:
    toc: true
  docx:
    toc: true