project:
  type: website
  title: "Software Modeling and Verification"
  output-dir: ../_site/fr

website:
  # Language switching setup

  navbar:
    # background: primary
    search: true
    # Right side for language selector
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html

  sidebar:
    style: docked
    search: true
    collapse-level: 1
    
    contents:
      - section: "Cours"
        contents: "ch*.qmd"
      - section: "Exercices"
        contents: "s*.qmd"


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
  pdf:
    toc: true
  docx: 
    toc: true